services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./assets:/app/assets
      - ./assets_served:/app/assets_served
      - ./media:/app/media
      - static_volume:/app/assets_served
      - media_volume:/app/media
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - SMS_API_KEY=${SMS_API_KEY}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
    depends_on:
      - mariadb
      - redis
    networks:
      - prago_network
    env_file:
      - .env

  mariadb:
    image: focker.ir/mariadb:latest
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always
    command: [
      '--innodb-flush-method=O_DIRECT',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - prago_network
    env_file:
      - .env

  redis:
    image: redis:6.2
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - prago_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/assets_served
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - prago_network

volumes:
  mariadb_volume:
  redis_data:
  static_volume:
  media_volume:

networks:
  prago_network:
    name: prago_network
    driver: bridge