# Generated by Django 4.1.13 on 2025-03-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام تگ')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ تگ')),
                ('content_type', models.CharField(choices=[('course', 'دوره'), ('blog', 'بلاگ'), ('both', 'هردو')], default='both', max_length=20, verbose_name='نوع محتوا')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ دسته\u200cبندی')),
                ('content_type', models.CharField(choices=[('course', 'دوره'), ('blog', 'بلاگ'), ('both', 'هردو')], default='both', max_length=20, verbose_name='نوع محتوا')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
    ]
