# Generated by Django 4.1.13 on 2025-03-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='latin_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام لاتین دسته\u200cبندی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='latin_name',
            field=models.CharField(default='', max_length=50, verbose_name='نام لاتین تگ'),
            preserve_default=False,
        ),
    ]
