# Generated by Django 4.2 on 2025-03-17 16:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کارمند است'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, help_text='شماره تماس یا با فرمت: 09123456789, یا با فرمت: +989123456789 نوشته شود', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(?:\\+98|0)9\\d{9}$', 'فرمت شماره وارد شده نادرست است')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(blank=True, help_text='شماره تماس یا با فرمت: 09123456789, یا با فرمت: +989123456789 نوشته شود', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(?:\\+98|0)9\\d{9}$', 'فرمت شماره وارد شده نادرست است')], verbose_name='شماره تماس'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='نام مدرس')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی مدرس')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ مدرس')),
                ('biography', models.TextField(blank=True, verbose_name='بیوگرافی مدرس')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل مدرس',
                'verbose_name_plural': 'پروفایل\u200cهای مدرسین',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='شبکه\u200cهای اجتماعی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='تحصیلات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='نام سازمان')),
                ('organization_slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ سازمان')),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='organizer_logos/', verbose_name='لوگو سازمان')),
                ('organization_website', models.URLField(blank=True, verbose_name='وب\u200cسایت سازمان')),
                ('organization_description', models.TextField(blank=True, verbose_name='درباره سازمان')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس')),
                ('verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل برگزارکننده',
                'verbose_name_plural': 'پروفایل\u200cهای برگزارکنندگان',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='نام مدرس')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی مدرس')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ مدرس')),
                ('biography', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل نویسنده',
                'verbose_name_plural': 'پروفایل\u200cهای نویسندگان',
            },
        ),
    ]
