# Generated by Django 4.1.13 on 2025-03-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_email_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسندگان'},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'برگزارکننده', 'verbose_name_plural': 'برگزارکنندگان'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'مدرسین'},
        ),
    ]
