# Generated by Django 4.1.13 on 2025-03-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_author_options_alter_organizer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسنده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'برگزارکننده', 'verbose_name_plural': 'برگزارکننده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربرها'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'مدرس\u200cها'},
        ),
    ]
