# Generated by Django 4.2 on 2025-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_author_options_alter_organizer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='author_avatars/', verbose_name='تصویر نویسنده'),
        ),
    ]
