# Generated by Django 4.2 on 2025-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='author_avatars/', verbose_name='تصویر مدرس'),
        ),
    ]
