# Generated by Django 4.2 on 2025-05-05 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import support.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='شماره تیکت')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('billing', 'Billing'), ('technical', 'Technical')], max_length=100, verbose_name='دپارتمان')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='open', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='تیکت')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=support.models.ticket_attachment_path, verbose_name='فایل')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_size', models.PositiveIntegerField(verbose_name='حجم فایل (بایت)')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیوست پیام',
                'verbose_name_plural': 'پیوست\u200cهای پیام',
            },
        ),
    ]
