# Generated by Django 4.2 on 2025-06-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0002_category_latin_name_tag_latin_name'),
        ('accounts', '0006_teacher_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='تصویر شاخص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('review', 'در بازبینی'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='accounts.author', verbose_name='نویسنده')),
                ('categories', models.ManyToManyField(limit_choices_to={'content_type__in': ['blog', 'both']}, related_name='blog_posts', to='taxonomy.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('tags', models.ManyToManyField(limit_choices_to={'content_type__in': ['blog', 'both']}, related_name='blog_posts', to='taxonomy.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'نوشته',
                'verbose_name_plural': 'نوشته\u200cها',
                'ordering': ['-published_at'],
            },
        ),
    ]
