# Generated by Django 4.2 on 2025-06-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_category_latin_name_tag_latin_name'),
        ('accounts', '0006_teacher_avatar'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-published_at'], 'verbose_name': 'نوشته', 'verbose_name_plural': 'نوشته\u200cها'},
        ),
        migrations.AddField(
            model_name='post',
            name='average_read_time',
            field=models.PositiveIntegerField(default=5, verbose_name='زمان متوسط مطالعه (دقیقه)'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='پین شده'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها'),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='accounts.author', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'content_type__in': ['blog', 'both']}, related_name='blog_posts', to='taxonomy.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/%d/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'content_type__in': ['blog', 'both']}, related_name='blog_posts', to='taxonomy.tag', verbose_name='تگ\u200cها'),
        ),
    ]
