# Generated by Django 4.1.13 on 2025-03-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_author_options_alter_organizer_options_and_more'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='شماره فصل')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان فصل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات فصل')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='cover_image', verbose_name='تصویر دوره')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر دوره')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ دوره')),
                ('description', models.TextField(verbose_name='توضیحات کامل دوره')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='قیمت')),
                ('special_offer_price', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='قیمت ویژه')),
                ('special_offer_start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع پیشنهاد ویژه')),
                ('special_offer_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان پیشنهاد ویژه')),
                ('intro_video_link', models.URLField(verbose_name='لینک ویدیو معرفی')),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='مجموع ساعات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('attributes', models.ManyToManyField(related_name='courses', to='courses.attribute', verbose_name='ویژگی\u200cها')),
                ('categories', models.ManyToManyField(related_name='courses', to='taxonomy.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('organizers', models.ManyToManyField(related_name='organized_courses', to='accounts.organizer', verbose_name='برگزار کنندگان')),
                ('tags', models.ManyToManyField(related_name='courses', to='taxonomy.tag', verbose_name='تگ\u200cها')),
                ('teachers', models.ManyToManyField(related_name='teaching_courses', to='accounts.teacher', verbose_name='مدرسین')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اپیزود')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ اپیزود')),
                ('type', models.CharField(choices=[('video', 'ویدیو'), ('file', 'فایل'), ('text', 'متن'), ('quiz', 'آزمون')], default='video', max_length=10, verbose_name='نوع')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episode_thumbnails', verbose_name='تصویر بند انگشتی')),
                ('content_url', models.URLField(verbose_name='آدرس محتوا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حجم فایل')),
                ('word_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد کلمات')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='courses.chapter', verbose_name='فصل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'اپیزود',
                'verbose_name_plural': 'اپیزودها',
                'ordering': ['chapter', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
