# Generated by Django 4.1.13 on 2025-03-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='slug',
        ),
    ]
