# Generated by Django 4.1.13 on 2025-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_author_options_alter_organizer_options_and_more'),
        ('courses', '0002_remove_episode_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='latin_title',
            field=models.CharField(default='', max_length=100, verbose_name='تیتر لاتین دوره'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='organizers',
            field=models.ManyToManyField(related_name='organized_courses', to='accounts.organizer', verbose_name='برگزار کننده\u200cها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_courses', to='accounts.teacher', verbose_name='مدرس\u200cها'),
        ),
    ]
