# Generated by Django 4.1.13 on 2025-03-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_latin_title_alter_course_organizers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddField(
            model_name='episode',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
    ]
