# Generated by Django 4.2 on 2025-04-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_published_at_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='دوره'),
            preserve_default=False,
        ),
    ]
