# Generated by Django 4.2 on 2025-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_chapter_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نقشه راه')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ نقشه راه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('cover_image', models.ImageField(upload_to='roadmap_cover_image', verbose_name='تصویر نقشه راه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('courses', models.ManyToManyField(related_name='roadmaps', to='courses.course', verbose_name='دوره\u200cها')),
            ],
            options={
                'verbose_name': 'نقشه راه',
                'verbose_name_plural': 'نقشه\u200cهای راه',
            },
        ),
    ]
