# Generated by Django 4.2 on 2025-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون'),
        ),
    ]
