# Generated by Django 4.2 on 2025-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_attribute_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='icon',
            field=models.CharField(blank=True, choices=[('Book', 'Book'), ('Clock', 'Clock'), ('VideoCircle', 'Video Circle'), ('Teacher', 'Teacher'), ('NoteFavorite', 'Note Favorite'), ('Chart', 'Chart'), ('Calendar', 'Calendar'), ('Layer', 'Layer'), ('Code', 'Code'), ('People', 'People'), ('Lock', 'Lock'), ('Rocket', 'Rocket'), ('Prago', 'Prago'), ('default', 'Default (Clock)')], max_length=50, null=True, verbose_name='آیکون'),
        ),
    ]
