# Generated by Django 4.2 on 2025-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_attribute_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['order'], 'verbose_name': 'اپیزود', 'verbose_name_plural': 'اپیزودها'},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب'),
        ),
    ]
