# Generated by Django 4.2 on 2025-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_episode_options_alter_episode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='مجموع ساعات'),
        ),
    ]
