# Generated by Django 4.2 on 2025-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='خلاصه'),
        ),
    ]
