# Generated by Django 4.2 on 2025-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='special_offer_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان پیشنهاد ویژه'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='special_offer_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='قیمت ویژه'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='special_offer_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع پیشنهاد ویژه'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='قیمت اصلی'),
        ),
    ]
